version: '3.8'

services:
  elastic:
    image: elastic:latest
    environment:
      - RUST_LOG=debug
    volumes:
      - ./elastic/src:/app/src
    depends_on:
      - elasticsearch
  
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  rust-app-data:
